travis:
  secure:
    BINSTAR_TOKEN: S0wpuviPRJiPdGa9kaNzi7eqLpBik/JDl1sPId+5ac9HQiqjgTZL5aWqqAQF2g5MA7QJGnwussrAbeQCooq6ws2NboXsX0J6TB8XgBEnU/6Za/RBPk+qD6lwX+klrJBwQg6MzkMfPVPsVJdEF2REbB6hOZyd1emct3LRBDwp6wx0DrJ0ayHt4ox92pd8AEcafBYRBZiJtSOi+YV1MSmod9BbDkFSnpbtGngHd+2U4kgn+3EfoNLgczPys5E3kVs70acs7urE3U4wqq7y4YJanseWOJ4JDEWSUUwlXMhjBsyXY0jnn/biBzT+/vUTq4ntPx8wcR+dlO8k03MZiFakrqLYJVHPDGLT3bIbTIz+g9YRe3R9AXMPJbzl14llH+AT12SSJxw+6RYtmYIkbo8CBEq79Op1muqDsyHeQ/194ricriG0yrXkMMWA45NwWJ7rnQHJKSYAcecgM1HnJU0uRx2xuBXOVH0VbvDHcQn4q04UlWktaVNbT2bR3iJpR1IOP2meV6R98gaG07VMBtuPwg83lG4hp0g6nvAebJkuML8yte3ebJ2hYWzAZXWmheFVYrfO8iSjLze/5ebVKZtJ27nQY/k+aFMvMnQpUOzcNg7HJ1FzYoMDgl7oQ4uUj5w1W6t5kEICzgNtyi36pl669t1RDTlwmv7f/7N1BRtT68g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
